package com.rumor.mesh.plugin.meshtastic

import com.rumor.mesh.plugin.meshtastic.MeshtasticProtobuf.Reader
import com.rumor.mesh.plugin.meshtastic.MeshtasticProtobuf.Writer
import com.rumor.mesh.plugin.meshtastic.MeshtasticProtobuf.fieldNumber
import com.rumor.mesh.plugin.meshtastic.MeshtasticProtobuf.wireType

/**
 * Typed views over the Meshtastic protobufs we touch.
 *
 * Only the fields used by a text bridge are modelled. New firmware adds fields
 * regularly; [MeshtasticProtobuf.Reader.skipField] keeps us forward-compatible
 * so the bridge survives firmware upgrades without our code changes.
 *
 * Field numbers come from the Meshtastic protobuf source of truth:
 *     https://github.com/meshtastic/protobufs/tree/master/meshtastic
 * (mesh.proto, portnums.proto). Confirmed against firmware ~2.4.x at time of
 * authoring; field numbers are wire-compatible going back to 2.0.
 */
internal object MeshtasticMessages {

    // ── PortNum ───────────────────────────────────────────────────────────────

    /**
     * From portnums.proto. We only act on TEXT_MESSAGE_APP — everything else
     * (telemetry, position, routing, neighbor info, etc.) is ignored.
     * Including only what we use keeps the bridge's surface area small.
     */
    const val PORT_TEXT_MESSAGE_APP = 1

    // ── Data (mesh.proto, inside MeshPacket) ──────────────────────────────────

    /**
     * Decoded `Data` carries the actual message payload. Field numbers:
     *   1  portnum    varint
     *   2  payload    bytes
     */
    data class Data(val portnum: Int, val payload: ByteArray) {
        // equals/hashCode auto-generated by data class; data class compares
        // ByteArray by reference. Acceptable here — we don't deduplicate Data
        // instances anywhere, just construct them on send and decompose on receive.

        fun encode(): ByteArray = Writer().apply {
            writeInt32(1, portnum)
            writeLengthDelimited(2, payload)
        }.toByteArray()

        companion object {
            fun decode(r: Reader): Data {
                var portnum = 0
                var payload = ByteArray(0)
                while (r.hasMore()) {
                    val tag = r.readInt()
                    when (fieldNumber(tag)) {
                        1 -> portnum = r.readInt()
                        2 -> payload = r.readBytes()
                        else -> r.skipField(wireType(tag))
                    }
                }
                return Data(portnum, payload)
            }
        }
    }

    // ── MeshPacket ────────────────────────────────────────────────────────────

    /**
     * The transport-level packet. Field numbers (subset):
     *   1  from        fixed32       — sender node number
     *   2  to          fixed32       — recipient (0xFFFFFFFF = broadcast)
     *   3  channel     varint        — channel index
     *   4  decoded     Data sub-msg  — populated when the radio has the channel key
     *   8  id          fixed32       — packet ID (used as the AES nonce LSBs)
     *  10  hop_limit   varint        — TTL on the LoRa side
     *
     * If `decoded` is missing but the encrypted payload (field 5) is present,
     * the radio couldn't decrypt for us (channel key mismatch). We drop those
     * — bridging encrypted-blob noise into Rumor would just spam users.
     */
    data class MeshPacket(
        val from: Int = 0,
        val to: Int = BROADCAST_NODE,
        val channel: Int = 0,
        val decoded: Data? = null,
        val id: Int = 0,
        val hopLimit: Int = 3,
    ) {
        /**
         * Encode for inclusion as a sub-message inside ToRadio. We set just
         * the fields needed to *send*: from defaults to 0 (radio fills its
         * own), to=broadcast, channel=0 (primary), decoded payload, fresh id.
         * Outbound hop_limit is set on the radio side; omitting it lets
         * firmware use its configured default.
         */
        fun encode(): ByteArray = Writer().apply {
            writeFixed32(2, to)                    // BROADCAST_NODE = -1 = 0xFFFFFFFF wire-side
            writeInt32(3, channel)
            decoded?.let { writeLengthDelimited(4, it.encode()) }
            if (id != 0) writeFixed32(8, id)
        }.toByteArray()

        companion object {
            const val BROADCAST_NODE = -1  // 0xFFFFFFFF as a signed int

            fun decode(r: Reader): MeshPacket {
                var from = 0
                var to = BROADCAST_NODE
                var channel = 0
                var decoded: Data? = null
                var id = 0
                var hop = 3
                while (r.hasMore()) {
                    val tag = r.readInt()
                    when (fieldNumber(tag)) {
                        1 -> from = r.readFixed32()
                        2 -> to = r.readFixed32()
                        3 -> channel = r.readInt()
                        4 -> decoded = r.readSubMessage { Data.decode(it) }
                        8 -> id = r.readFixed32()
                        10 -> hop = r.readInt()
                        else -> r.skipField(wireType(tag))
                    }
                }
                return MeshPacket(from, to, channel, decoded, id, hop)
            }
        }
    }

    // ── FromRadio (device → app) ──────────────────────────────────────────────

    /**
     * `FromRadio` is a oneof of many possible payload types. We only care
     * about field 11 (packet, a MeshPacket). All other variants are skipped:
     *   2  my_info       — node info, useful for the synthetic sender ID
     *   3  node_info     — peer roster, not bridged
     *   4  config        — settings, irrelevant to bridging
     *   5  log_record    — debug
     *   6  config_complete_id — handshake terminator
     *   8  rebooted      — power events
     *   ... etc
     *
     * The bridge only reads `packet` so we return null for everything else.
     */
    fun decodeFromRadioPacket(frame: ByteArray): MeshPacket? {
        val r = Reader(frame)
        while (r.hasMore()) {
            val tag = r.readInt()
            if (fieldNumber(tag) == 11) {
                return r.readSubMessage { MeshPacket.decode(it) }
            }
            r.skipField(wireType(tag))
        }
        return null
    }

    // ── ToRadio (app → device) ────────────────────────────────────────────────

    /**
     * `ToRadio` field numbers used here:
     *   1  packet         MeshPacket — outbound
     *   3  want_config_id varint — kicks off the initial handshake; the radio
     *                      responds by streaming MyNodeInfo, Channels, etc.,
     *                      ending with a FromRadio with config_complete_id
     *                      equal to this value.
     *
     * We only encode `packet` here. Config handshake is optional for a
     * minimal bridge — text messages flow without it as long as the radio's
     * primary channel matches our outbound channel index.
     */
    fun encodeToRadioPacket(packet: MeshPacket): ByteArray = Writer().apply {
        writeLengthDelimited(1, packet.encode())
    }.toByteArray()
}
